title: appleJuiceNET
description: >-
    appleJuice - dein P2P Client aus Deutschland
lang: de_DE
favicon: favicon.png
github_username: applejuicenet

permalink: pretty
timezone: Europe/Berlin

shields_style: for-the-badge

footer_menu: footer_menu

# Build settings
#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
plugins:
    - github-pages

defaults:
    -   scope:
            path: ""
        values:
            hero_height: is-small
            hero_image: /assets/images/apple-on-grass-red.jpg


