title: appleJuiceNETZ
description: >-
  appleJuice - seit 2002 dein P2P Client aus Deutschland
lang: de_DE
favicon: favicon.png
github_username: applejuicenetz
docker_username: applejuicenetz

permalink: pretty
timezone: Europe/Berlin

shields_style: for-the-badge

footer_menu: footer_menu

# Build settings
#heme: bulma-clean-theme # enable local builds in docker
remote_theme: chrisrhymes/bulma-clean-theme

plugins:
  - github-pages
  - jemoji

defaults:
  - scope:
      path: ""
    values:
      hero_height: is-small
      hero_image: /assets/images/apple-on-grass-red.jpg


